/*
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */

#pragma once

#include "yrt-pet/datastruct/projection/ProjectionProperties.hpp"
#include "yrt-pet/operators/OperatorProjectorDevice.cuh"
#include "yrt-pet/operators/ProjectorUtils.hpp"
#include "yrt-pet/utils/GPUKernelUtils.cuh"

#include <cfloat>
#include <cuda_runtime.h>
#include <curand_kernel.h>

namespace yrt
{

enum SIDDON_DIR
{
	DIR_X = 0b001,
	DIR_Y = 0b010,
	DIR_Z = 0b100
};

__device__ inline curandState
    setupMultiRays(unsigned long seed, unsigned long id,
                   const float3& det1Orient, const float3& det2Orient,
                   float3& parallelToTrans1, float3& parallelToTrans2)
{
	curandState state;
	curand_init(seed, id, 0, &state);

	constexpr float3 vectParallelToZ{0, 0, 1};

	parallelToTrans1 = cross(det1Orient, vectParallelToZ);
	parallelToTrans2 = cross(det2Orient, vectParallelToZ);

	normalize(parallelToTrans1);
	normalize(parallelToTrans2);
	return state;
}

template <bool UseParallelLines = false>
__device__ void moveLineToRandomOffset(curandState& state, float3& p1,
                                       float3& p2,
                                       const float3& parallelToTrans1,
                                       const float3& parallelToTrans2,
                                       const CUScannerParams& scannerParams)
{
	constexpr float3 vectParallelToZ{0, 0, 1};

	// Note: The LORs generated by the MR siddon for each coincidence won't be
	//  parallel
	const float rand_i_1 = curand_uniform(&state) - 0.5f;
	const float rand_j_1 = curand_uniform(&state) - 0.5f;

	float rand_i_2, rand_j_2;
	if constexpr (UseParallelLines)
	{
		rand_i_2 = rand_i_1;
		rand_j_2 = rand_j_1;
	}
	else
	{
		rand_i_2 = curand_uniform(&state) - 0.5f;
		rand_j_2 = curand_uniform(&state) - 0.5f;
	}

	p1 = p1 + vectParallelToZ * (rand_i_1 * scannerParams.crystalSize_z) +
	     parallelToTrans1 * (rand_j_1 * scannerParams.crystalSize_trans);
	p2 = p2 + vectParallelToZ * (rand_i_2 * scannerParams.crystalSize_z) -
	     parallelToTrans2 * (rand_j_2 * scannerParams.crystalSize_trans);
}

// Arguments:
//  value: value to use either to accumulate the forward projection or to
//    backproject on the image
//  pd_image: device pointer to the image
//  pd_updater: device pointer to the updater
//  p1Init: Endpoint of the line to project. The "Init" part refers to the fact
//    that it will be moved by the multi-ray Siddon if IsMultiRay == true and
//    numRays > 1
//  p2Init: Other endpoint of the line to project
//  n1: Orientation of the detector of p1Init. This must be a unit vector
//  n2: Orientation of the detector of p2Init
//  dynamicFrame: Frame of the current event (information used by the updater)
//  pd_tofHelper: device pointer to the TimeOfFlightHelper object. Ignored if
//    HasTOF == false
//  tofValue: TOF value to use in picoseconds. Ignored if HasTOF == false
//  scannerParams: Scanner parameters
//  imgParams: Image parameters
//  numRays: Number of rays to forward/backward project by the multi-ray Siddon.
//    Ignored if IsMultiRay == false
//  randomId: ID to use for curand_init for the multi-ray Siddon. Ignored if
//    IsMultiRay == false
template <bool IsForward, bool HasTOF, bool IsIncremental, bool IsMultiRay,
          bool UseUpdater>
__device__ void
    projectSiddon(float& value, float* pd_image, UpdaterPointer pd_updater,
                  float3 p1Init, float3 p2Init, float3 n1, float3 n2,
                  frame_t dynamicFrame, const TimeOfFlightHelper* pd_tofHelper,
                  float tofValue, CUScannerParams scannerParams,
                  CUImageParams imgParams, int numRays, size_t randomId)
{
	float localValue = 0.0f;

	if constexpr (!IsForward)
	{
		localValue = value;
	}

	curandState state;
	float3 parallelToTrans1, parallelToTrans2;
	if constexpr (IsMultiRay)
	{
		state = setupMultiRays(13, randomId, n1, n2, parallelToTrans1,
		                       parallelToTrans2);
		if constexpr (!IsForward)
		{
			localValue /= static_cast<float>(numRays);
		}
	}

	for (int i_line = 0; i_line < numRays; i_line++)
	{
		float3 p1 = p1Init;
		float3 p2 = p2Init;
		if constexpr (IsMultiRay)
		{
			// Modify p1 and p2 for multi-ray
			if (i_line > 0)
			{
				moveLineToRandomOffset(state, p1, p2, parallelToTrans1,
				                       parallelToTrans2, scannerParams);
			}
		}

		const float3 p1_minus_p2 = p1 - p2;

		// 1. Intersection with FOV
		float t0;
		float t1;
		// Intersection with (centered) FOV cylinder
		float A = (p2.x - p1.x) * (p2.x - p1.x) + (p2.y - p1.y) * (p2.y - p1.y);
		float B = 2.0f * ((p2.x - p1.x) * p1.x + (p2.y - p1.y) * p1.y);
		float C = p1.x * p1.x + p1.y * p1.y -
		          imgParams.fovRadius * imgParams.fovRadius;
		float Delta = B * B - 4 * A * C;
		if (A != 0.0)
		{
			if (Delta <= 0.0)
			{
				t0 = 1.0;
				t1 = 0.0;
				continue;
			}
			t0 = (-B - sqrt(Delta)) / (2 * A);
			t1 = (-B + sqrt(Delta)) / (2 * A);
		}
		else
		{
			t0 = 0.0;
			t1 = 1.0;
		}

		float d_norm = norm3df(p1_minus_p2.x, p1_minus_p2.y, p1_minus_p2.z);
		bool flat_x = (p1.x == p2.x);
		bool flat_y = (p1.y == p2.y);
		bool flat_z = (p1.z == p2.z);
		float inv_p12_x = flat_x ? 0.0f : 1.0f / (p2.x - p1.x);
		float inv_p12_y = flat_y ? 0.0f : 1.0f / (p2.y - p1.y);
		float inv_p12_z = flat_z ? 0.0f : 1.0f / (p2.z - p1.z);
		int dir_x = (inv_p12_x >= 0.0) ? 1 : -1;
		int dir_y = (inv_p12_y >= 0.0) ? 1 : -1;
		int dir_z = (inv_p12_z >= 0.0) ? 1 : -1;

		// 2. Intersection with volume
		const int nx = imgParams.nx;
		const int ny = imgParams.ny;
		const int nz = imgParams.nz;
		const float imgLength_x = imgParams.length_x;
		const float imgLength_y = imgParams.length_y;
		const float imgLength_z = imgParams.length_z;
		const int num_xy = nx * ny;
		const float dx = imgParams.vx;
		const float dy = imgParams.vy;
		const float dz = imgParams.vz;
		float inv_dx = 1.0f / dx;
		float inv_dy = 1.0f / dy;
		float inv_dz = 1.0f / dz;

		float x0 = -imgLength_x * 0.5f;
		float x1 = imgLength_x * 0.5f;
		float y0 = -imgLength_y * 0.5f;
		float y1 = imgLength_y * 0.5f;
		float z0 = -imgLength_z * 0.5f;
		float z1 = imgLength_z * 0.5f;
		float ax_min, ax_max, ay_min, ay_max, az_min, az_max;
		util::get_alpha(-0.5f * imgLength_x, 0.5f * imgLength_x, p1.x, p2.x,
		                inv_p12_x, ax_min, ax_max);
		util::get_alpha(-0.5f * imgLength_y, 0.5f * imgLength_y, p1.y, p2.y,
		                inv_p12_y, ay_min, ay_max);
		util::get_alpha(-0.5f * imgLength_z, 0.5f * imgLength_z, p1.z, p2.z,
		                inv_p12_z, az_min, az_max);
		float amin = max(0.0f, t0, ax_min, ay_min, az_min);
		float amax = min(1.0f, t1, ax_max, ay_max, az_max);
		if (HasTOF)
		{
			float amin_tof, amax_tof;
			pd_tofHelper->getAlphaRange(amin_tof, amax_tof, d_norm, tofValue);
			amin = max(amin, amin_tof);
			amax = min(amax, amax_tof);
		}

		float a_cur = amin;
		float a_next = -1.0f;
		float x_cur = (inv_p12_x > 0.0f) ? x0 : x1;
		float y_cur = (inv_p12_y > 0.0f) ? y0 : y1;
		float z_cur = (inv_p12_z > 0.0f) ? z0 : z1;
		if ((inv_p12_x >= 0.0f && p1.x > x1) ||
		    (inv_p12_x < 0.0f && p1.x < x0) ||
		    (inv_p12_y >= 0.0f && p1.y > y1) ||
		    (inv_p12_y < 0.0f && p1.y < y0) ||
		    (inv_p12_z >= 0.0f && p1.z > z1) || (inv_p12_z < 0.0f && p1.z < z0))
		{
			continue;
		}
		// Move starting point inside FOV
		float ax_next = flat_x ? FLT_MAX : ax_min;
		if (!flat_x)
		{
			int kx =
			    (int)ceil(dir_x * (a_cur * (p2.x - p1.x) - x_cur + p1.x) / dx);
			x_cur += kx * dir_x * dx;
			ax_next = (x_cur - p1.x) * inv_p12_x;
		}
		float ay_next = flat_y ? FLT_MAX : ay_min;
		if (!flat_y)
		{
			int ky =
			    (int)ceil(dir_y * (a_cur * (p2.y - p1.y) - y_cur + p1.y) / dy);
			y_cur += ky * dir_y * dy;
			ay_next = (y_cur - p1.y) * inv_p12_y;
		}
		float az_next = flat_z ? FLT_MAX : az_min;
		if (!flat_z)
		{
			int kz =
			    (int)ceil(dir_z * (a_cur * (p2.z - p1.z) - z_cur + p1.z) / dz);
			z_cur += kz * dir_z * dz;
			az_next = (z_cur - p1.z) * inv_p12_z;
		}
		// Pixel location (move pixel to pixel instead of calculating
		// position for each intersection)
		bool flag_first = true;
		int vx = -1;
		int vy = -1;
		int vz = -1;
		// The dir variables operate as binary bit-flags to determine in
		// which direction the current pixel should move: format 0bzyx
		// (where z, y and x are bits set to 1 when the pixel should move in
		// the corresponding direction, e.g. 0b101 moves in the z and x
		// directions)
		short dir_prev = -1;
		short dir_next = -1;

		// Prepare data pointer (this assumes that the data is stored as a
		// contiguous array)
		float* raw_img_ptr = pd_image;
		size_t offset_img = 0;

		float ax_next_prev = ax_next;
		float ay_next_prev = ay_next;
		float az_next_prev = az_next;

		// 3. Integrate along ray
		bool flag_done = false;
		while (a_cur < amax && !flag_done)
		{
			// Find next intersection (along x, y or z)
			dir_next = 0b000;
			if (ax_next_prev <= ay_next_prev && ax_next_prev <= az_next_prev)
			{
				a_next = ax_next;
				x_cur += dir_x * dx;
				ax_next = (x_cur - p1.x) * inv_p12_x;
				dir_next |= SIDDON_DIR::DIR_X;
			}
			if (ay_next_prev <= ax_next_prev && ay_next_prev <= az_next_prev)
			{
				a_next = ay_next;
				y_cur += dir_y * dy;
				ay_next = (y_cur - p1.y) * inv_p12_y;
				dir_next |= SIDDON_DIR::DIR_Y;
			}
			if (az_next_prev <= ax_next_prev && az_next_prev <= ay_next_prev)
			{
				a_next = az_next;
				z_cur += dir_z * dz;
				az_next = (z_cur - p1.z) * inv_p12_z;
				dir_next |= SIDDON_DIR::DIR_Z;
			}
			// Clip to FOV range
			if (a_next > amax)
			{
				a_next = amax;
			}
			if (a_cur >= a_next)
			{
				ax_next_prev = ax_next;
				ay_next_prev = ay_next;
				az_next_prev = az_next;
				continue;
			}
			// Determine pixel location
			float tof_weight = 1.f;
			float a_mid = 0.5f * (a_cur + a_next);
			if constexpr (HasTOF)
			{
				tof_weight = pd_tofHelper->getWeight(
				    d_norm, tofValue, a_cur * d_norm, a_next * d_norm);
			}
			if (!IsIncremental || flag_first)
			{
				vx = (int)((p1.x + a_mid * (p2.x - p1.x) + imgLength_x / 2) *
				           inv_dx);
				vy = (int)((p1.y + a_mid * (p2.y - p1.y) + imgLength_y / 2) *
				           inv_dy);
				vz = (int)((p1.z + a_mid * (p2.z - p1.z) + imgLength_z / 2) *
				           inv_dz);
				offset_img = vz * num_xy + vy * nx;
				flag_first = false;
				if (vx < 0 || vx >= nx || vy < 0 || vy >= ny || vz < 0 ||
				    vz >= nz)
				{
					flag_done = true;
				}
			}
			else
			{
				if (dir_prev & SIDDON_DIR::DIR_X)
				{
					vx += dir_x;
					if (vx < 0 || vx >= nx)
					{
						flag_done = true;
					}
				}
				if (dir_prev & SIDDON_DIR::DIR_Y)
				{
					vy += dir_y;
					if (vy < 0 || vy >= ny)
					{
						flag_done = true;
					}
					else
					{
						offset_img += dir_y * nx;
					}
				}
				if (dir_prev & SIDDON_DIR::DIR_Z)
				{
					vz += dir_z;
					if (vz < 0 || vz >= nz)
					{
						flag_done = true;
					}
					else
					{
						offset_img += dir_z * num_xy;
					}
				}
			}
			if (flag_done)
			{
				continue;
			}
			dir_prev = dir_next;
			float weight = (a_next - a_cur) * d_norm;
			const size_t numVoxelsPerFrame = nx * ny * nz;
			const size_t imageOffset = vx + offset_img;
			if constexpr (HasTOF)
			{
				weight *= tof_weight;
			}

			if constexpr (IsForward)
			{
				if constexpr (UseUpdater)
				{
					localValue +=
					    (*pd_updater)
					        ->forwardUpdate(weight, raw_img_ptr, imageOffset,
					                        dynamicFrame, numVoxelsPerFrame);
				}
				else
				{
					localValue +=
					    weight * raw_img_ptr[dynamicFrame * numVoxelsPerFrame +
					                         imageOffset];
				}
			}
			else
			{
				if constexpr (UseUpdater)
				{
					(*pd_updater)
					    ->backUpdate(localValue, weight, raw_img_ptr,
					                 imageOffset, dynamicFrame,
					                 numVoxelsPerFrame);
				}
				else
				{
					float output = value * weight;
					atomicAdd(raw_img_ptr + dynamicFrame * numVoxelsPerFrame +
					              imageOffset,
					          output);
				}
			}
			a_cur = a_next;
			ax_next_prev = ax_next;
			ay_next_prev = ay_next;
			az_next_prev = az_next;
		}
	}

	if constexpr (IsForward)
	{
		if constexpr (IsMultiRay)
		{
			localValue /= static_cast<float>(numRays);
		}
		value = localValue;
	}
}

// Wrapper that translates (some of) the given arguments into the appropriate
//  template arguments and calls the function above. Could be slower but
//  simplifies calls inside the kernel. Always uses isIncremental
template <bool IsForward, bool UseUpdater>
__device__ void projectSiddonDefault(
    float& value, float* pd_image, UpdaterPointer pd_updater, float3 p1Init,
    float3 p2Init, float3 n1, float3 n2, frame_t dynamicFrame,
    const TimeOfFlightHelper* pd_tofHelper, float tofValue,
    CUScannerParams scannerParams, CUImageParams imgParams, int numRays,
    size_t randomId)
{
	if (pd_tofHelper == nullptr)
	{
		// No TOF
		if (numRays == 1)
		{
			// Non-Multi-Ray
			projectSiddon<IsForward, false, true, false, UseUpdater>(
			    value, pd_image, pd_updater, p1Init, p2Init, n1, n2,
			    dynamicFrame, nullptr, 0.0f, scannerParams, imgParams, 1,
			    randomId);
		}
		else
		{
			// Multi-Ray
			projectSiddon<IsForward, false, true, true, UseUpdater>(
			    value, pd_image, pd_updater, p1Init, p2Init, n1, n2,
			    dynamicFrame, nullptr, 0.0f, scannerParams, imgParams, numRays,
			    randomId);
		}
	}
	else
	{
		// TOF enabled
		if (numRays == 1)
		{
			// Non-Multi-Ray
			projectSiddon<IsForward, true, true, false, UseUpdater>(
			    value, pd_image, pd_updater, p1Init, p2Init, n1, n2,
			    dynamicFrame, pd_tofHelper, tofValue, scannerParams, imgParams,
			    1, randomId);
		}
		else
		{
			// Multi-Ray
			projectSiddon<IsForward, true, true, true, UseUpdater>(
			    value, pd_image, pd_updater, p1Init, p2Init, n1, n2,
			    dynamicFrame, pd_tofHelper, tofValue, scannerParams, imgParams,
			    numRays, randomId);
		}
	}
}


template <bool IsForward, bool HasTOF, bool IsIncremental, bool IsMultiRay,
          bool UseUpdater>
__global__ void projectSiddon_kernel(
    float* pd_projValues, float* pd_image, UpdaterPointer pd_updater,
    const ProjectionPropertyManager* pd_projPropManager,
    const PropertyUnit* pd_projectionProperties,
    const TimeOfFlightHelper* pd_tofHelper, CUScannerParams scannerParams,
    CUImageParams imgParams, int p_numRays, size_t batchSize)
{
	const long eventId = blockIdx.x * blockDim.x + threadIdx.x;

	if (eventId < batchSize)
	{
		float& value = pd_projValues[eventId];

		const float* lor = pd_projPropManager->getDataPtr<float>(
		    pd_projectionProperties, eventId, ProjectionPropertyType::LOR);
		static_assert(sizeof(Line3D) == sizeof(float3) * 2);
		float3 p1Init{lor[0], lor[1], lor[2]};
		float3 p2Init{lor[3], lor[4], lor[5]};

		const float3 imageOffset =
		    make_float3(imgParams.off_x, imgParams.off_y, imgParams.off_z);

		p1Init -= imageOffset;
		p2Init -= imageOffset;

		float3 n1{};
		float3 n2{};
		if constexpr (IsMultiRay)
		{
			const float* detOrient = pd_projPropManager->getDataPtr<float>(
			    pd_projectionProperties, eventId,
			    ProjectionPropertyType::DET_ORIENT);
			n1 = {detOrient[0], detOrient[1], detOrient[2]};
			n2 = {detOrient[3], detOrient[4], detOrient[5]};
		}

		float tofValue = 0.0f;
		if constexpr (HasTOF)
		{
			const float* tofValuePtr = pd_projPropManager->getDataPtr<float>(
			    pd_projectionProperties, eventId, ProjectionPropertyType::TOF);
			tofValue = *tofValuePtr;
		}

		frame_t dynamicFrame = 0;
		if (pd_projPropManager->has(ProjectionPropertyType::DYNAMIC_FRAME))
		{
			dynamicFrame = *pd_projPropManager->getDataPtr<frame_t>(
			    pd_projectionProperties, eventId,
			    ProjectionPropertyType::DYNAMIC_FRAME);
		}

		if (dynamicFrame >= 0)
		{
			projectSiddon<IsForward, HasTOF, IsIncremental, IsMultiRay,
			              UseUpdater>(value, pd_image, pd_updater, p1Init,
			                          p2Init, n1, n2, dynamicFrame,
			                          pd_tofHelper, tofValue, scannerParams,
			                          imgParams, p_numRays, eventId);
		}
		else
		{
			// If the frame is disabled, do nothing
			// If doing a forward projection, populate the value at zero
			if constexpr (IsForward)
			{
				value = 0.0f;
			}
		}
	}
}

}  // namespace yrt
